import pytest

from deepeval.metrics import ContextualPrecisionMetric
from deepeval.test_case import LLMTestCase

from utils.LLMUtils import get_response_from_llm
from utils.TestDataUtils import load_data_sets


# Terminology
# - Contextual Precision: The degree to which the answer provided by the LLM is relevant to the input question.
# - Threshold: A score above which the answer is considered relevant.
# - input: The question or prompt given to the LLM.
# - expected_output: The expected answer from the test data.
# - actual_output: The answer generated by the LLM.
# - retrieval_context: The context retrieved by the LLM to generate the answer.
@pytest.mark.parametrize("build_test_case",
                         load_data_sets("FaithfulnessDataFeed.json"),
                         indirect=True)
def test_contextual_precision(build_test_case,
                              model_name,
                              expected_threshold):
    contextual_precision_metric = ContextualPrecisionMetric(threshold=expected_threshold,
                                                            model=model_name,
                                                            include_reason=True)
    contextual_precision_metric.measure(build_test_case)
    assert contextual_precision_metric.score >= expected_threshold, (
        f"Score {contextual_precision_metric.score:.2f} below threshold {expected_threshold}. Reason: {contextual_precision_metric.reason}"
    )


@pytest.fixture
def build_test_case(request):
    test_data = request.param

    response_from_rag_llm = get_response_from_llm(test_data)
    # Extract the response and retrieved context
    retrieved_contexts = [doc["page_content"] for doc in response_from_rag_llm["retrieved_docs"]]

    test_case = LLMTestCase(
        input=test_data["input"],
        expected_output=test_data["reference"],  # reference is the expected output from test_data
        actual_output=response_from_rag_llm["answer"],
        retrieval_context=retrieved_contexts
    )

    return test_case
